Catch asp checkout errors and abort
archlinux/archlinux-repro pull request #109
Opened 2022-03-16 10:27 UTC by inglor

This is cause probably because the job ran before the svntogit synced
properly.

Signed-off-by: Leonidas Spyropoulos <artafinde@archlinux.org>

2022-03-16 11:08 UTC, Foxboron requested changes

2022-03-16 11:08 UTC, Foxboron commented on repro.in
> +if [ $? -ne 0 ]; then
```suggestion
if ! asp checkout $pkgbase; then
```

2022-03-16 12:04 UTC, inglor commented
Testing by manually editing the repro to change the `pkgbase` to some garbage. Then the repro failed with an exit code of `1`
```
[..]
error: unknown package: foobar-leo
ERROR: Failed checkout foobar-leo
  -> Delete snapshot for foobar-leo_105683...
 ~/workspace/archlinux/svn-community/makedumpfile/trunk
> echo $?
1
```

2022-03-16 14:35 UTC, Foxboron approved these changes

2022-03-25 08:33 UTC, jelly approved these changes

2022-03-25 08:43 UTC, merged